import './list'
import './create/create-hotel-debt'
import './create/create-hotel-paid'
import './create/review-page'
import './create/apply-for-hotel'
import './detail-list/list'
import './detail-list/edit'
import './detail-list/detail'
